{{- $image := .Values.image | default dict -}}
apiVersion: batch/v1
kind: Job
metadata:
 name: {{ include "delivery-service.fullname" . }}
 annotations:
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-weight": "-1"
  "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "delivery-service.fullname" . }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}-db-migrations
        image: "{{ $image.repository }}:{{ $image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ $image.pullPolicy }}
        command: ["dotnet"]
        args: ["Api.dll", "update"]
        envFrom:
          - secretRef:
              name: delivery-service-secret-db-migration